version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword

    ports:
      - "3310:3306" # MySQL is accessible on port 3306
    volumes:
      - db-data:/var/lib/mysql # Persistent database data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Run init script at startup

  web:
    build: .
    container_name: vulnerable-web
    volumes:
      - ./src:/var/www/html # PHP code is mounted here
    ports:
      - "8081:80" # Web app is accessible at localhost:8081
    depends_on:
      - db # Waits for the database to start

volumes:
  db-data: # Named volume for persistent data
